# Generated by Django 5.2.1 on 2025-08-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
