# Generated by Django 5.2.1 on 2025-09-16 13:25

import django.db.models.deletion
import rooms.models
from django.db import migrations, models
from rooms.models import room_image_upload_to

class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_picture_alter_room_price_booking_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=room_image_upload_to),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=rooms.models.room_image_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
        ),
    ]
