# Generated by Django 5.2.1 on 2025-09-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_picture_roomimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
